---
- name: first playbook
  hosts: node1.example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: install packages
    package:
      name:
        - httpd
      state: latest
  - name: start httpd
    service: name=httpd state=started
  - name: edit text
    lineinfile:
      path: /var/www/html/index.html
      line: Welcome to my web server
      create: yes
  - name: give port access
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
...