---
- name: first playbook
  hosts: node1.example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: install packages
    package:
      name:
        - httpd
        - apache
      state: latest 
...